export {
  CLIENT_OPEN_EXTERNAL,
  CLIENT_OPEN_PATH,
  CLIENT_SHOW_IN_FOLDER,
  CLIENT_CONFIRM_DIALOG,
  CLIENT_OPEN_FILE_DIALOG,
  LOCAL_CLIENT_CAPABILITIES,
  requestClientOpenExternal,
  requestClientOpenPath,
  requestClientShowInFolder,
  requestClientConfirmDialog,
  requestClientOpenFileDialog,
  type ConfirmDialogSpec,
  type FileDialogSpec,
} from '@craft-agent/server-core/transport'
