#!/usr/bin/env bun
/**
 * IPC channel snapshot regenerator.
 *
 * Reads RPC_CHANNELS from `packages/shared/src/protocol/channels.ts` and
 * regenerates the auto-generated `EXPECTED_CHANNELS` block inside
 * `apps/electron/src/shared/__tests__/ipc-channels.test.ts`.
 *
 * Run after adding/removing/renaming any RPC_CHANNELS entry:
 *   bun run scripts/ipc-inventory.ts
 *
 * The test file marks the generated block with the comments:
 *   // Auto-generated by scripts/ipc-inventory.ts — DO NOT edit by hand.
 *   ...
 *   // End auto-generated
 *
 * Everything between those markers is overwritten on each run; everything
 * outside is preserved.
 */

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const REPO_ROOT = join(import.meta.dir, '..')
const CHANNELS_PATH = join(
  REPO_ROOT,
  'packages',
  'shared',
  'src',
  'protocol',
  'channels.ts',
)
const TEST_PATH = join(
  REPO_ROOT,
  'apps',
  'electron',
  'src',
  'shared',
  '__tests__',
  'ipc-channels.test.ts',
)

const BEGIN_MARKER = '// Auto-generated by scripts/ipc-inventory.ts — DO NOT edit by hand.'
const END_MARKER = '// End auto-generated'

// ---------------------------------------------------------------------------
// 1. Extract wire strings from the RPC_CHANNELS definition.
// ---------------------------------------------------------------------------

const channelsSource = readFileSync(CHANNELS_PATH, 'utf-8')

const channelBlockMatch = channelsSource.match(
  /export const RPC_CHANNELS = \{([\s\S]*?)\} as const/,
)
if (!channelBlockMatch) {
  console.error(`ERROR: Could not find "RPC_CHANNELS" definition in ${CHANNELS_PATH}`)
  process.exit(1)
}

// Capture every leaf `KEY: 'value'` pair regardless of nesting depth. The
// regex is line-anchored so it doesn't match inside multi-line block comments
// the way a non-anchored variant would (block comments live in the file too).
const wireRegex = /^\s*\w+\s*:\s*'([^']+)'/gm
const wireValues: string[] = []
let match: RegExpExecArray | null
while ((match = wireRegex.exec(channelBlockMatch[1] ?? '')) !== null) {
  wireValues.push(match[1]!)
}

if (wireValues.length === 0) {
  console.error('ERROR: No wire-format strings extracted — regex broken?')
  process.exit(1)
}

// ---------------------------------------------------------------------------
// 2. Validate (no duplicates) and sort.
// ---------------------------------------------------------------------------

const seen = new Set<string>()
const duplicates: string[] = []
for (const v of wireValues) {
  if (seen.has(v)) duplicates.push(v)
  seen.add(v)
}
if (duplicates.length > 0) {
  console.error(`ERROR: Duplicate wire-format strings:\n  ${duplicates.join('\n  ')}`)
  process.exit(1)
}

const sorted = [...wireValues].sort()

// ---------------------------------------------------------------------------
// 3. Build the new generated block and rewrite the test file.
// ---------------------------------------------------------------------------

const generatedBlock = [
  BEGIN_MARKER,
  'const EXPECTED_CHANNELS: string[] = [',
  ...sorted.map((s) => `  '${s}',`),
  ']',
  '',
  'const EXPECTED_COUNT = EXPECTED_CHANNELS.length',
  END_MARKER,
].join('\n')

const testSource = readFileSync(TEST_PATH, 'utf-8')

const beginIdx = testSource.indexOf(BEGIN_MARKER)
const endIdx = testSource.indexOf(END_MARKER)
if (beginIdx < 0 || endIdx < 0 || endIdx < beginIdx) {
  console.error(
    `ERROR: Couldn't find generated-block markers in ${TEST_PATH}.\n` +
      `Expected "${BEGIN_MARKER}" then "${END_MARKER}".`,
  )
  process.exit(1)
}

const before = testSource.slice(0, beginIdx)
const after = testSource.slice(endIdx + END_MARKER.length)
const updatedSource = `${before}${generatedBlock}${after}`

if (updatedSource === testSource) {
  console.log(`✓ ${TEST_PATH} already up to date (${sorted.length} channels)`)
  process.exit(0)
}

writeFileSync(TEST_PATH, updatedSource, 'utf-8')

// ---------------------------------------------------------------------------
// 4. Summary.
// ---------------------------------------------------------------------------

console.log(`✓ Regenerated ${TEST_PATH}`)
console.log(`  Channels: ${sorted.length}`)

// Quick sanity preview: count entries by wire prefix so reviewers can spot
// missing namespaces at a glance.
const byPrefix = new Map<string, number>()
for (const wire of sorted) {
  const idx = wire.indexOf(':')
  const prefix = idx >= 0 ? wire.slice(0, idx) : wire
  byPrefix.set(prefix, (byPrefix.get(prefix) ?? 0) + 1)
}
console.log(`  Prefixes: ${byPrefix.size}`)
for (const [prefix, count] of [...byPrefix.entries()].sort()) {
  console.log(`    ${prefix.padEnd(28)} ${count}`)
}
